ARG NODE_VERSION=26.7 
FROM node:${NODE_VERSION}-alpine AS builder

WORKDIR /the/workdir/path

COPY ./react-app/package-lock.json /the/workdir/path/
COPY ./react-app/tsconfig.app.json /the/workdir/path/
COPY ./react-app/vite.config.ts /the/workdir/path/

RUN apt npm install \
    neovim\
    git\
    /