#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - ca-certificates
  - curl
  - docker.io
  - nginx

users:
  - default
  - name: admin
    gecos: Instance Administrator
    groups:
      - sudo
    shell: /bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    lock_passwd: true

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - systemctl enable nginx
  - systemctl restart nginx
  - nginx -t

final_message: "cloud-init completed after $UPTIME seconds."
