#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true
ssh_pwauth: false

packages:
  - ca-certificates
  - curl
  - docker.io
  - nginx

runcmd:
  - systemctl disable --now ssh
  - systemctl enable --now amazon-ssm-agent
  - systemctl enable docker
  - systemctl start docker
  - systemctl enable nginx
  - systemctl restart nginx
  - nginx -t

final_message: "cloud-init completed after $UPTIME seconds."
